# Generated by Django 3.2.3 on 2021-05-24 02:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_comment_comment_users'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='comment_users',
            new_name='comment_user',
        ),
    ]
