# Generated by Django 3.2.3 on 2021-05-27 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_delete_like'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='like_users',
        ),
    ]
